### ISSUE TITLE
Question for `Products are accumulated in binary32` and `Sum starts from largest element`

### ISSUE THREAD

**Issue by xinyi-li7** [north-numerical-computing/tensor-cores-numerical-behavior#2]
Dear author, 

I was reviewing the numerical computations in your scripts [tc_test_numerics-A100-bf16.cu](https://github.com/north-numerical-computing/tensor-cores-numerical-behavior/blob/master/tc_test_numerics-A100-bf16.cu) and [tc_test_numerics-T4-A100-binary16.cu](https://github.com/north-numerical-computing/tensor-cores-numerical-behavior/blob/master/tc_test_numerics-T4-A100-binary16.cu). I noticed that you've set the initial values of the first row in matrix A as 0.5 and the first column of matrix B as $2^{-24}$.

This setup results in the calculation $2^{-1}*2^{-24} + 2^{-1}*2^{-24} + 2^{-1}*2^{-24} +1 + 2^{-24}$, which indeed aligns with the conclusion in your paper.

However, when I modify the initial values of the first row in A to 1, as suggested in the original paper, the output yields 3f800002. It seems to suggest that the accurate result is obtained and that the summation doesn't necessarily start with the largest number and not involve 4 rounding errors. 

Could you please confirm if my understanding is correct? Any insights you can share would be greatly appreciated.

**Comment by xinyi-li7** [comment]
In the end of the paper, they did say A100 has one extra bit for significand.

**Comment by mmikaitis** [comment]
Hi. You conclusion was correct. Apologies for not replying - there was no notification.
