### ISSUE TITLE
Curly brackets missing?

### ISSUE THREAD

**Issue by jglaser** [north-numerical-computing/tensor-cores-numerical-behavior#3]
This looks like a scoping error

https://github.com/north-numerical-computing/tensor-cores-numerical-behavior/blob/3230e9a5c81aedd2c5f17745df3e4febccd5e3da/tc_test_numerics-T4-A100-binary16.cu#L274-L276

**Comment by mmikaitis** [comment]
Fixed. The expected behaviour of the test should not have been altered by this bug as for j>0 h_b[j-1] was reset back to minsubnormal16 as expected. Many thanks for reporting it.
